#!/usr/bin/env bash

set -e

# Run a command or default server
if [ $# -gt 0 ]; then
    "$@"
else
    cd /srv/www/backend; composer install && php artisan serve --host="${LARAVEL_HOST:=0.0.0.0}" --port="${LARAVEL_PORT:=5000}"
fi
